# Numpy --08/06/2022

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
print(a)

[1 2 3 4]


In [6]:
a.shape

(4,)

In [7]:
a.ndim

1

In [8]:
max(a)

4

In [10]:
np.mean(a)

2.5

In [11]:
type(a)

numpy.ndarray

In [12]:
np.std(a)

1.118033988749895

In [3]:
a=np.array([1,2,3,4,5,6])

In [4]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
a.resize(3,2)

In [6]:
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
a.resize(2,3)

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a=np.array([1,2,3,4,5,6])

In [11]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a

array([1, 2, 3, 4, 5, 6])

In [13]:
b=np.array([5,5,5])

In [15]:
np.linspace(0,11,5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [16]:
11/5

2.2

In [8]:
np.linspace(0,20,7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [5]:
np.linspace(0,11,4)

array([ 0.        ,  3.66666667,  7.33333333, 11.        ])

18.3